#!/bin/bash

#################################################################
###  Copy Right (c): 2021, Rishabh Dutta                      ###  
###  Author: Rishabh Dutta                                    ###               
###  Email : rd873@mst.edu                                    ###
###  Univ. : Missouri University of Science and Technology    ###   
#################################################################

#stackSentinel.py generates all configuration and run files required to be
#executed on a stack of Sentinel-1 TOPS data. When stackSentinel.py is executed
#for a given workflow (-W option) a configs and run_files folder is generated.
#No processing is performed at this stage. Within the run_files folder different
#run_#_description files are contained which are to be executed as shell scripts
#in the run number order. Each of these run scripts call specific configure files
#contained in the “configs” folder which call ISCE in a modular fashion. The
#configure and run files will change depending on the selected workflow. To
#make run_# files executable, change the file permission accordingly
#(e.g., chmod +x run_01_unpack_slc).

# all the scripts are run as a sudoer for permissions to write on the external drive

sudo mkdir stackprocessing
cd stackprocessing
sudo env "PATH=$PATH" stackSentinel.py -H     #To see workflow examples,
sudo env "PATH=$PATH" stackSentinel.py -h     #To get an overview of all the configurable parameters

# before running stackSentinel.py, make sure all the zipped SLCs are in one folder
sudo mkdir SLCs
cd SLCs

# if you already downloaded the download.py and asf_datapool.csv files, then run
sudo env "PATH=$PATH" python ./download-all-*.py . asf-datapool-results-*.csv
# you will have to provide ASF username and password

# get the dem for the region in the DEM folder
cd ..
sudo mkdir DEM
cd DEM
sudo env "PATH=$PATH" dem.py -a stitch -b 31 33 -114 -113 -k  -r -l  -s 1 -n rishabhgeo -w password

# you might want to use -f flag if some of the tiles are not available

# once you get the DEM downloaded, run the following to make the DEM files ISCE readable
sudo env "PATH=$PATH" fixImageXml.py -i demLat*.dem -f

# if dem.py didn't work and you had to manually download srtm 30m resolution DEM
sudo env "PATH=$PATH" gdal_merge.py tiffs/*.tif -o mydem.tif
sudo env "PATH=$PATH" gdalwarp -t_srs '+proj=longlat +datum=WGS84' mydem.tif mydem2.tif
sudo env "PATH=$PATH" gdal_translate -of ISCE mydem2.tif mydem.dem
sudo env "PATH=$PATH" fixImageXml.py -i mydem.dem -f

# Next, check if the orbit restituted files or precise orbit files are present.
# Recently the location of orbit files have been moved to another location
# https://s1qc.asf.alaska.edu/

# calibration files AUX_CAL_* are placed in folder /media/12TB-2/Projects/Haiti/Rishabh/AUX/
# if the folder is empty, get the files from https://s1qc.asf.alaska.edu/aux_cal/
# get index.html from the page sources (right click and choose Inspect)
sudo env "PATH=$PATH" awk '{print "wget --user=rishabhgeo --password='password' https://s1qc.asf.alaska.edu/aux_cal/"substr($2,7,50)}' index.html  | sudo dd of=getallfiles.txt
sudo chmod +x getallfiles.txt
sudo ./getallfiles.txt

# precise orbits files AUX_POEORB_* are placed in folder /media/12TB-2/Projects/Haiti/Rishabh/AUX_POEORB/
# if the folder is empty, get the files from https://s1qc.asf.alaska.edu/aux_poeorb/
# get index.html from the page sources (right click and choose Inspect)
sudo env "PATH=$PATH" awk '{print "wget --user=rishabhgeo --password='password' https://s1qc.asf.alaska.edu/aux_poeorb/"substr($2,7,77)}' index.html  | sudo dd of=getallfiles.txt
sudo chmod +x getallfiles.txt
sudo ./getallfiles.txt


####################stackSentinel.py#############################################
# example for the case of Haiti ascending track 04  
cd ..
sudo mkdir stack
cd stack

sudo env "PATH=$PATH" stackSentinel.py -s /media/12TB-1/data/S1/Haiti/Rishabh/AT4/ -d /media/12TB-2/Projects/Haiti/Rishabh/DEM/demLat_N17_N21_Lon_W075_W069_wgs84.dem -a /media/12TB-2/Projects/Haiti/Rishabh/AUX/ -o /media/12TB-2/Projects/Haiti/Rishabh/AUX_POEORB/ -c 3 -b ’17.78 20.17 -74.68 -71.79’ -m 20170215

