#!/bin/bash

#################################################################
###  Copy Right (c): 2022, Rishabh Dutta                      ###
###  Author: Rishabh Dutta                                    ###
###  Email : rd873@mst.edu                                    ###
###  Univ. : Missouri University of Science and Technology    ###
#################################################################

# Steps to install Fringe - estimate deformation time-series by 
# exploiting interferometric covariance matrix for distributed scatterers
# (DS) and the phase history of pixels that exhibit very little temporal
# variation (PS)

# installing on Ubuntu OS without sudo access. 

# create a conda environment for running fringe
conda create -n fringe python=3.8
conda activate fringe

# install prerequisites
conda install cmake
conda install cython
conda install gdal
conda install libgdal
conda install armadillo
conda install lapack
conda install blas
conda install -c conda-forge isce2
conda install gxx_linux-64
# libgdal is installed when installing gdal

# ** IMPORTANT ** set environment variables for isce2 before installing fringe
# Fringe install won't work otherwise - has to be corrected in fringe installation guide
ISCE_HOME=/home/rd873/anaconda3/envs/isce2/lib/python3.7/site-packages/isce
ISCE_STACK=/home/rd873/anaconda3/envs/isce2/share/isce2
PATH=$ISCE_HOME/bin:$ISCE_HOME/applications:$ISCE_STACK/topsStack:$ISCE_STACK/stripmapStack:$ISCE_STACK/prepStackToStaMPS/bin:$PATH
PYTHONPATH=/home/rd873/anaconda3/envs/isce2/lib/python3.7/site-packages:$PYTHONPATH
# edit the lines according to your path

# now install fringe
# follow steps in https://github.com/isce-framework/fringe/blob/main/docs/install.md
cd ~/softwares
rm -rf fringe
mkdir fringe
cd fringe

mkdir install build src
cd src
git clone https://github.com/isce-framework/fringe.git

cd ../build
CXX=${CXX} cmake -DCMAKE_INSTALL_PREFIX=../install ../src/fringe
make all
make install

# now add environment variables for fringe
export PATH=$PATH:/home/rd873/softwares/fringe/install/bin
export PYTHONPATH=$PYTHONPATH:/home/rd873/softwares/fringe/install/python
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/rd873/softwares/fringe/install/lib
# edit the lines according to your path
















